name: Build and Test (Galactic)
on:
  push:
    branches: [ galactic ]
  pull_request:
    branches: [ galactic ]
  schedule:
    - cron: '0 21 * * *'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Build rmoss_mindvision_driver
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: galactic
          vcs-repo-file-url: "${{ github.workspace }}/dependency.repos"
          skip-tests: true
      - name: Test rmoss_mindvision_driver
        run: |
          source /opt/ros/galactic/setup.sh
          cd ros_ws
          colcon test --packages-select rmoss_mindvision_driver --event-handlers console_cohesion+ --return-code-on-test-failure
